export const downloadBlob = (content, filename, contentType) => {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const generateAuditCSV = (logs) => {
  const header = 'Timestamp,User,Action,Entity,Details,Type\n';
  const rows = logs.map(log => 
    `"${log.timestamp}","${log.user}","${log.action}","${log.entity}","${log.details}","${log.type}"`
  ).join('\n');
  return header + rows;
};

export const generateEvaluationReport = (bidder, evaluations) => {
  const score = bidder.match_score || 0;
  const status = score >= 80 ? 'HIGHLY QUALIFIED' : score >= 60 ? 'BORDERLINE MATCH' : 'MISMATCH / MISSING SKILLS';

  let report = `RESUME EVALUATOR ATS CANDIDATE MATCH REPORT\n`;
  report += `====================================\n\n`;
  report += `CANDIDATE NAME: ${bidder.name}\n`;
  report += `CANDIDATE ID:   ${bidder.id}\n`;
  report += `JOB ROLE ID:    ${bidder.tender_id}\n`;
  report += `DATE EVALUATED: ${new Date().toLocaleDateString()}\n`;
  report += `ATS MATCH SCORE: ${Math.round(score)}%\n`;
  report += `EVALUATION STATUS: ${status}\n\n`;
  
  if (bidder.is_disqualified) {
    report += `!!! MISSING MANDATORY REQUIREMENT !!!\n`;
    report += `Reason: ${bidder.disqualification_reason}\n\n`;
  }

  report += `REQUIREMENTS BREAKDOWN:\n`;
  report += `-----------------------\n`;
  
  evaluations.forEach(ev => {
    const verdictLabel = ev.verdict === 'eligible' ? 'FULLY MATCHED' : ev.verdict === 'ineligible' ? 'MISSING' : 'BORDERLINE';
    report += `[${verdictLabel}] Requirement: ${ev.criterion_id}\n`;
    report += `Extracted Value: ${ev.extracted_value}\n`;
    report += `AI Reasoning: ${ev.reasoning}\n`;
    if (ev.evidence_snippet) {
      report += `Evidence Snippet: "${ev.evidence_snippet}"\n`;
    }
    if (ev.action_required) {
      report += `ATS Improvement Suggestion: ${ev.action_required}\n`;
    }
    report += `Source Document: ${ev.source_document || 'Resume'} (Page ${ev.source_page})\n`;
    report += `-----------------------\n\n`;
  });
  
  report += `\nGENERATED BY: RESUME EVALUATOR AI ATS PARSING SYSTEM\n`;
  return report;
};
